# Generated by Django 3.2.3 on 2021-11-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.TextField(blank=True, null=True)),
                ('brightness', models.BooleanField(default=False)),
                ('contrast', models.BooleanField(default=False)),
                ('sharpness', models.BooleanField(default=False)),
                ('flip_left_right', models.BooleanField(default=False)),
                ('flip_top_bottom', models.BooleanField(default=False)),
                ('smoothness', models.BooleanField(default=False)),
                ('grayscale', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'PhotoData',
            },
        ),
        migrations.CreateModel(
            name='PhotoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(default='default.jpg', upload_to='edited_images/')),
            ],
            options={
                'verbose_name_plural': 'PhotoImage',
            },
        ),
    ]
