# Generated by Django 3.2.3 on 2021-11-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0003_photooriginal'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoimage',
            name='photoname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photoimage',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='Uploaded_Images/'),
        ),
        migrations.AlterField(
            model_name='photooriginal',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='Original_Images/'),
        ),
    ]
