# Generated by Django 3.2.3 on 2021-11-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0004_auto_20211121_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoimage',
            old_name='photoname',
            new_name='title',
        ),
        migrations.AddField(
            model_name='photooriginal',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
