# Generated by Django 3.2.3 on 2021-11-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0006_auto_20211121_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoimage',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='Original_Images/'),
        ),
    ]
