# Generated by Django 3.2.3 on 2021-11-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0007_alter_photoimage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoimage',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='Uploaded_Images/'),
        ),
    ]
