# Generated by Django 3.2.3 on 2021-11-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0008_alter_photoimage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoimage',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
