# Generated by Django 3.2.3 on 2021-11-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0009_photoimage_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoimage',
            name='edited',
        ),
    ]
