# Generated by Django 3.2.3 on 2021-11-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoeditor', '0010_remove_photoimage_edited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoOriginal',
        ),
    ]
